name: print_date
on: [push]

jobs:
  job1:
    name: first-job
    runs-on: ubuntu-latest
    steps:
    - name: first-job-step
      run: date

  job2:
    name: second-job
    runs-on: windows-latest
    steps:
    - run: date

  job3:
    name: third-job
    runs-on: macos-latest
    steps:
    - run: date
 
  job4:
    name: depended-job
    needs: [job1,job2,job3]
    runs-on: ubuntu-latest
    steps:
    - run: date
